import { describe, expect, it, vi, beforeEach, MockInstance } from 'vitest';
import { GET } from '@/app/api/v1/packages/explanation/route';
import { GenerateExplanationUseCase } from '@/application/use-cases/GenerateExplanationUseCase';

// Mock openai
vi.mock('openai', () => {
  return {
    default: class {
      chat = {
        completions: {
          create: vi.fn()
        }
      };
    }
  };
});

// Mock PrismaClient to prevent actual DB connections
vi.mock('@prisma/client', () => {
  return {
    PrismaClient: class {}
  };
});

describe('GET /api/v1/packages/explanation', () => {
  let executeSpy: MockInstance;

  beforeEach(() => {
    executeSpy = vi.spyOn(GenerateExplanationUseCase.prototype, 'execute');
    executeSpy.mockReset();
  });

  const createRequest = (url: string) => {
    return new Request(`http://localhost${url}`);
  };

  it('1. Valid request returns HTTP 200 with explanation', async () => {
    executeSpy.mockResolvedValue('This is a test explanation generated by AI.');

    const response = await GET(createRequest('/api/v1/packages/explanation?name=react&registry=npm'));
    expect(response.status).toBe(200);
    const data = await response.json();

    expect(data.explanation).toBe('This is a test explanation generated by AI.');
    expect(executeSpy).toHaveBeenCalledWith('react', 'npm');
  });

  it('2. Missing name returns HTTP 400', async () => {
    const response = await GET(createRequest('/api/v1/packages/explanation?registry=npm'));
    expect(response.status).toBe(400);
    const data = await response.json();
    expect(data.error).toBe('invalid_request');
  });

  it('3. Invalid registry returns HTTP 400', async () => {
    const response = await GET(createRequest('/api/v1/packages/explanation?name=react&registry=cargo'));
    expect(response.status).toBe(400);
    const data = await response.json();
    expect(data.error).toBe('invalid_request');
  });

  it('4. Returns 404 when score is not found', async () => {
    executeSpy.mockRejectedValue(new Error('Score not found'));

    const response = await GET(createRequest('/api/v1/packages/explanation?name=unknown&registry=npm'));
    expect(response.status).toBe(404);
    const data = await response.json();
    expect(data.error).toBe('not_found');
    expect(data.message).toBe('Score not found. Explanation requires an already-persisted score.');
  });

  it('5. Returns 400 when package status is invalid (e.g. insufficient_data)', async () => {
    executeSpy.mockRejectedValue(new Error('Invalid package status'));

    const response = await GET(createRequest('/api/v1/packages/explanation?name=small-pkg&registry=npm'));
    expect(response.status).toBe(400);
    const data = await response.json();
    expect(data.error).toBe('invalid_request');
    expect(data.message).toBe('Cannot generate explanation for a package with insufficient data or unsupported status.');
  });

  it('6. Returns 500 when AI generation fails (without exposing internal details)', async () => {
    const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    executeSpy.mockRejectedValue(new Error('Failed to generate AI explanation.'));

    const response = await GET(createRequest('/api/v1/packages/explanation?name=react&registry=npm'));
    expect(response.status).toBe(500);
    const data = await response.json();
    
    expect(data.error).toBe('internal_error');
    expect(data.message).toBe('Failed to generate AI explanation.');
    
    consoleSpy.mockRestore();
  });
});
